export const colorByType = {
    normal: 'gray', 
    fire: '#FE9441', 
    water: '#8AC4CD', 
    grass: '#7FB535', 
    electric: 'gold', 
    ice: 'lightblue', 
    fighting: '#CA2E30', 
    poison: '#CA60B1', 
    ground: '#B65F39', 
    flying: 'skyblue', 
    psychic: 'pink', 
    bug: '#5ACB2C', 
    rock: '#B4B49B', 
    ghost: 'indigo', 
    dragon: 'royalblue', 
    dark: 'black', 
    steel: 'silver', 
    fairy: 'hotpink'
};